version: '3.8'

services:
  dms_backend:
    build: .
    command: gunicorn dms_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - env.staging
    #entrypoint: "/bin/bash"
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    environment:
    - POSTGRES_USER=test_dms
    - POSTGRES_PASSWORD=test_dms
    - POSTGRES_DB=test_dms