version: '3.8'

services:
  dms_backend:
    build: .
    command: gunicorn dms_backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - /root/dms/env.prod
    network_mode: "host"