# Generated by Django 3.0.3 on 2020-04-14 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=32)),
                ('long_name', models.CharField(max_length=200)),
                ('standard_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UC2Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=200)),
                ('file_standard_name', models.CharField(max_length=200, unique=True)),
                ('file', models.FileField(upload_to='')),
                ('keywords', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(default='test', max_length=200)),
                ('source', models.CharField(default='test', max_length=200)),
                ('institution', models.CharField(default='Not specified', max_length=200)),
                ('upload_date', models.DateTimeField(default='2020-04-14 07:33:06')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('licence', models.CharField(default='[UC]2 Open Licence', max_length=200)),
                ('is_invalid', models.BooleanField(default=False)),
                ('is_old', models.BooleanField(default=False)),
                ('has_warnings', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(default=False)),
                ('featureType', models.CharField(max_length=32)),
                ('data_content', models.CharField(max_length=200)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('acronym', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=3)),
                ('site', models.CharField(max_length=12)),
                ('origin_lon', models.FloatField(default=0.0)),
                ('origin_lat', models.FloatField(default=0.0)),
                ('campaign', models.CharField(max_length=6)),
                ('creation_time', models.CharField(max_length=23)),
                ('origin_time', models.CharField(max_length=23)),
                ('uploader', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('variables', models.ManyToManyField(related_name='datasets', to='data.Variable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
