# Generated by Django 3.0.3 on 2020-02-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UC2Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=200)),
                ('file_id', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('user_id', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('upload_date', models.DateTimeField(verbose_name='upload_date')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('feature_type', models.CharField(max_length=200)),
                ('data_content', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=32)),
                ('long_name', models.CharField(max_length=200)),
                ('standard_name', models.CharField(max_length=200)),
                ('data_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.UC2Observation')),
            ],
        ),
    ]
