# Generated by Django 3.0.3 on 2020-02-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uc2observation',
            name='license',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
