# Generated by Django 3.0.4 on 2020-04-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uc2observation',
            name='upload_date',
            field=models.DateTimeField(default='2020-04-03 16:43:46'),
        ),
    ]
