# Generated by Django 3.0.3 on 2020-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='data_file',
        ),
        migrations.AlterField(
            model_name='uc2observation',
            name='upload_date',
            field=models.DateTimeField(default='2020-04-12 15:58:15'),
        ),
        migrations.RemoveField(
            model_name='variable',
            name='variable_name',
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_name',
            field=models.ManyToManyField(max_length=32, to='data.UC2Observation'),
        ),
    ]
