# Generated by Django 3.0.3 on 2020-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200412_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='variable_name',
            new_name='variable',
        ),
        migrations.AlterField(
            model_name='uc2observation',
            name='upload_date',
            field=models.DateTimeField(default='2020-04-12 16:06:42'),
        ),
    ]
