# Generated by Django 3.0.3 on 2020-04-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200403_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='uc2observation',
            name='has_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uc2observation',
            name='has_warnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uc2observation',
            name='upload_date',
            field=models.DateTimeField(default='2020-04-09 19:41:24'),
        ),
    ]
