# Generated by Django 3.0.3 on 2020-04-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200412_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='in_datasets',
        ),
        migrations.AddField(
            model_name='uc2observation',
            name='variables',
            field=models.ManyToManyField(to='data.Variable'),
        ),
        migrations.AlterField(
            model_name='uc2observation',
            name='upload_date',
            field=models.DateTimeField(default='2020-04-12 16:24:36'),
        ),
    ]
