# Generated by Django 3.0.3 on 2020-04-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200412_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uc2observation',
            name='upload_date',
            field=models.DateTimeField(default='2020-04-14 05:50:07'),
        ),
        migrations.AlterField(
            model_name='uc2observation',
            name='variables',
            field=models.ManyToManyField(null=True, to='data.Variable'),
        ),
    ]
